package_rename_config:
  android:
    app_name: "Organized Camera"
    package_name: "com.andrexi.organized_camera"

  # ios:
  #   app_name: # (String) The display name of the ios app
  #   bundle_name: # (String) The bundle name of the ios app
  #   package_name: # (String) The product bundle identifier of the ios app

  # linux:
  #   app_name: # (String) The window title of the linux app
  #   package_name: # (String) The application id of the linux app
  #   exe_name: # (String) The executable name (binary name) of the linux app

  # macos:
  #   app_name: # (String) The product name of the macos app
  #   package_name: # (String) The product bundle identifier of the macos app
  #   copyright_notice: # (String) The product copyright of the macos app

  # web:
  #   app_name: # (String) The title and display name of the web app and PWA
  #   description: # (String) The description of the web app and PWA

  # windows:
  #   app_name: # (String) The window title & software name of the windows app
  #   organization: # (String) The organization name (company name) of the windows app
  #   copyright_notice: # (String) The legal copyright of the windows app
  #   exe_name: # (String) The executable name (binary name) of the windows app

  # flutter pub run package_rename:set